:heavy_plus_sign: Added PG21 paper
geoelements/geoelements.github.io pull request #2
Opened 2021-04-08 22:24 UTC by reihos

Added the 2021 Powders and Grain paper to the publications.

2021-04-08 22:32 UTC, kks32 requested changes
Could you please add your Abstract below?

2021-04-08 22:59 UTC, reihos commented
Like this?

2021-04-09 13:36 UTC, kks32 commented on _posts/publications/2021-01-04-multiphase-swrc.md
> +The soil water retention curve (SWRC) is the most commonly used relationship in the study of unsaturated soil. In this paper, the effect of porosity on the SWRC is investigated by numerically modelin
---

## Abstract

The soil water retention curve (SWRC) is the most commonly used relationship in the study of unsaturated soil. In this paper, the effect of porosity on the SWRC is investigated by numerically modeling unsaturated soil using the Shan-Chen multiphase Lattice Boltzmann Method. The shape of simulated SWRCs are compared against that predicted by the van Genuchten model, demonstrating a good fit except at low degrees of saturation. The simulated SWRCs show an increase in the air-entry value as porosity decreases.

2021-04-09 13:36 UTC, kks32 requested changes
Add the abstract below the line

2021-04-09 13:36 UTC, kks32 commented on _posts/publications/2021-01-04-multiphase-swrc.md
> +The soil water retention curve (SWRC) is the most commonly used relationship in the study of unsaturated soil. In this paper, the effect of porosity on the SWRC is investigated by numerically modelin
below the `---`

2021-04-09 18:09 UTC, kks32 approved these changes

2021-04-09 18:10 UTC, merged